config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  resources :timers
  resources :comments
  resources :posts
  resources :blogs
  root 'pages#home'

  get 'pages/measurements'

  get 'pages/about_me'
  
  get 'pages/recipe_posts'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/timer.rb
class Timer < ApplicationRecord
end

app/controllers/timers_controller.rb
class TimersController < ApplicationController
  before_action :set_timer, only: [:show, :edit, :update, :destroy]

  # GET /timers
  # GET /timers.json
  def index
    @timers = Timer.all
  end

  # GET /timers/1
  # GET /timers/1.json
  def show
    @timer1 = @timer.timer1 * 60
    # @timer2 = @timer.timer2
    # @timer3 = @timer.timer3
    # @timer4 = @timer.timer4
    # @timer5 = @timer.timer5
    
  end

  # GET /timers/new
  def new
    @timer = Timer.new
  end

  # GET /timers/1/edit
  def edit
  end

  # POST /timers
  # POST /timers.json
  def create
    @timer = Timer.new(timer_params)

    respond_to do |format|
      if @timer.save
        format.html { redirect_to @timer, notice: 'Timer was successfully created.' }
        format.json { render :show, status: :created, location: @timer }
      else
        format.html { render :new }
        format.json { render json: @timer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /timers/1
  # PATCH/PUT /timers/1.json
  def update
    respond_to do |format|
      if @timer.update(timer_params)
        format.html { redirect_to @timer, notice: 'Timer was successfully updated.' }
        format.json { render :show, status: :ok, location: @timer }
      else
        format.html { render :edit }
        format.json { render json: @timer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /timers/1
  # DELETE /timers/1.json
  def destroy
    @timer.destroy
    respond_to do |format|
      format.html { redirect_to timers_url, notice: 'Timer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_timer
      @timer = Timer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def timer_params
      params.require(:timer).permit(:timer_title, :timer1, :timer2, :timer3, :timer4, :timer5)
    end
end

app/helpers/timers_helper.rb
module TimersHelper
end

app/views/timers/_form.html.erb
<%= form_for(timer) do |f| %>
  <% if timer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(timer.errors.count, "error") %> prohibited this timer from being saved:</h2>

      <ul>
      <% timer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :timer_title %>
    <%= f.text_field :timer_title %>
  </div>

  <div class="field">
    <%= f.label :timer1 %>
    <%= f.number_field :timer1 %>
  </div>

  <!--<div class="field">-->
  <!--  <%#= f.label :timer2 %>-->
  <!--  <%#= f.number_field :timer2 %>-->
  <!--</div>-->

  <!--<div class="field">-->
  <!--  <%#= f.label :timer3 %>-->
  <!--  <%#= f.number_field :timer3 %>-->
  <!--</div>-->

  <!--<div class="field">-->
  <!--  <%#= f.label :timer4 %>-->
  <!--  <%#= f.number_field :timer4 %>-->
  <!--</div>-->

  <!--<div class="field">-->
  <!--  <%#= f.label :timer5 %>-->
  <!--  <%#= f.number_field :timer5 %>-->
  <!--</div>-->

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/timers/edit.html.erb
<h1>Editing Timer</h1>

<%= render 'form', timer: @timer %>

<%= link_to 'Show', @timer %> |
<%= link_to 'Back', timers_path %>

app/views/timers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Timers Page</h1>


<table>
  <thead>
    <tr>
      <!--<th>Timer title</th>-->
      <!--<th>Timer1</th>-->
      <!--<th>Timer2</th>-->
      <!--<th>Timer3</th>-->
      <!--<th>Timer4</th>-->
      <!--<th>Timer5</th>-->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @timers.each do |timer| %>
      <tr>
        <!--<td><%#= timer.timer_title %></td>-->
        <!--<td><%#= timer.timer1 %></td>-->
        <!--<td><%#= timer.timer2 %></td>-->
        <!--<td><%#= timer.timer3 %></td>-->
        <!--<td><%#= timer.timer4 %></td>-->
        <!--<td><%#= timer.timer5 %></td>-->
        <td><%= link_to "#{timer.timer_title}", timer %></td>
        <td><%= link_to 'Edit', edit_timer_path(timer) %></td>
        <td><%= link_to 'Destroy', timer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Timer', new_timer_path %>

app/views/timers/new.html.erb
<h1>New Timer</h1>

<%= render 'form', timer: @timer %>

<%= link_to 'Back', timers_path %>

app/views/timers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Timer title:</strong>
  <%= @timer.timer_title %>
</p>

<p>
  <strong>Timer1:</strong>
  <div class="clock"></div>
</p>

<!--<p>-->
<!--  <strong>Timer2:</strong>-->
<!--  <div class="clock2"></div>-->
<!--</p>-->

<!--<p>-->
<!--  <strong>Timer3:</strong>-->
<!--  <div class="clock3"></div>-->
<!--</p>-->

<!--<p>-->
<!--  <strong>Timer4:</strong>-->
<!--  <div class="clock4"></div>-->
<!--</p>-->

<!--<p>-->
<!--  <strong>Timer5:</strong>-->
<!--  <div class="clock5"></div>-->
<!--</p>-->

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/flipclock/0.7.8/flipclock.min.js"></script>

<script type="text/javascript">

	time_diff = <%= @timer1 %>;
// 	time_diff2 = <%#= @timer2 %>;
// 	time_diff3 = <%#= @timer3 %>;
// 	time_diff4 = <%#= @timer4 %>;
// 	time_diff5 = <%#= @timer5 %>;
	

	var clock = $('.clock').FlipClock(time_diff, {
		countdown: true
	});
// 	var clock2 = $('.clock2').FlipClock(time_diff2, {
// 		countdown: true
// 	});
// 	var clock3 = $('.clock3').FlipClock(time_diff3, {
// 		countdown: true
// 	});
// 	var clock4 = $('.clock4').FlipClock(time_diff4, {
// 		countdown: true
// 	});
// 	var clock5 = $('.clock5').FlipClock(time_diff5, {
// 		countdown: true
// 	});
	
</script>



<%= link_to 'Edit', edit_timer_path(@timer) %> |
<%= link_to 'Back', timers_path %>