config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  resources :timers
  resources :comments
  resources :posts
  resources :blogs
  root 'pages#home'

  get 'pages/measurements'

  get 'pages/about_me'
  
  get 'pages/recipe_posts'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChefApp</title>
    <%= csrf_meta_tags %>
  

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <div class="container test">
      <div class="row">
        <div class='nav'>
          <%= link_to "Home", root_path%>
          <%= link_to "Measurements", pages_measurements_path%>
          <%= link_to "My Recipes", posts_path%>
          <%= link_to "About me", pages_about_me_path%>
          <%= link_to "Blogs", blogs_path%>
          <%= link_to "Cooking Timers", timers_path%>
        </div>
        <p class="navbar-text pull-right">
          <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong>.
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
            <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
            <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
        </p>
      </div>
   </div>
     <% if notice %>
         <p class="alert alert-success"><%= notice %></p>
     <% end %>
     <% if alert %>
         <p class="alert alert-danger"><%= alert %></p>
     <% end %>
    <%= yield %>
  </body>
</html>